// ------------------------------------------------------------------------------
// <auto-generated>
//		This code was (partially) generated by CsWin32!
//		https://github.com/microsoft/CsWin32/
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591, CS1573, CS0465, CS0649, CS8019, CS1570, CS1584, CS1658, CS0436, CS8981

#region Using Directives
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;

using winmdroot = global::Windows.Win32;
#endregion

namespace Windows.Win32.Foundation;

[DebuggerDisplay( "{Value}" )]
public readonly struct BOOL : IEquatable<BOOL>
{
	/// <summary>
	/// The internal value of the Win32 BOOL
	/// </summary>
	public readonly int Value;

	public BOOL( int value ) => this.Value = value;
	public BOOL( bool value ) => this.Value = value ? 1 : 0;

	public static implicit operator bool( BOOL value ) => value.Value != 0;
	public static implicit operator BOOL( bool value ) => new BOOL( value );
	public static implicit operator int( BOOL value ) => value.Value;
	public static explicit operator BOOL( int value ) => new BOOL( value );
	public static bool operator ==( BOOL left, BOOL right ) => left.Value == right.Value;
	public static bool operator !=( BOOL left, BOOL right ) => !(left == right);

	/// <summary>
	/// Determines if the given BOOL is equal to this value
	/// </summary>
	/// <param name="other">BOOL to compare to</param>
	/// <returns>True if equal, otherwise false</returns>
	public bool Equals( BOOL other ) => this.Value == other.Value;
	/// <summary>
	/// Determines if the given object is equal to this value
	/// </summary>
	/// <param name="obj">object to compare to</param>
	/// <returns>True if equal, otherwise false</returns>
	public override bool Equals( object obj ) => obj is BOOL other && this.Equals( other );
	/// <summary>
	/// Gets the hash code of this BOOL value
	/// </summary>
	/// <returns>Int32 hash code</returns>
	public override int GetHashCode() => this.Value.GetHashCode();
};
